server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/mark-loy/springcloud-config.git
          search-paths:
            - springcloud-config
  # rabbitmq配置
  rabbitmq:
    host: 192.168.166.128
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka